## 行列演算の基礎

-ベクトルの定義
-行列の定義
-転置
-逆行列
-行列積

In [1]:
import numpy as np

In [5]:
# ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [7]:
#行列の定期
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [10]:
#転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [12]:
#逆行列
#線形代数　　linear algebra
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
#行列積
XX_inv = np.dot(X,X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# よくある間違い

In [15]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [16]:
x.T

array([1, 2, 3])

# Numpyでよく使う処理

In [19]:
X = np.array([
    [2,3,4],
    [1,2,3]
])
print(X)

[[2 3 4]
 [1 2 3]]


In [20]:
X.shape

(2, 3)

In [21]:
row, col = X.shape

In [22]:
row

2

In [23]:
col

3

In [26]:
for x in X:
    print(x)
    print('---')

[2 3 4]
---
[1 2 3]
---


# 演習問題

$\boldsymbol{X} = \begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 5 \\
1 & 3 & 4 \\
1 & 5 & 9 \\
\end{bmatrix}
,\\boldsymbol{y} = \begin{bmatrix}
1\\
5\\
6\\
8\\
\end{bmatrix}

$\boldsymbol{w} = (\boldsymbo{X} 入力方わからん


In [29]:
# Xの定義
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [36]:
# Yの定義
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [32]:
XtX = np.dot(X.T,X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [34]:
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [37]:
Xty = np.dot(X.T,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [38]:
w = np.dot(XtX_inv,Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [39]:
import sklearn

In [40]:
#重回帰分析のみ読込
from sklearn.linear_model import LinearRegression

In [50]:
#モデルの宣言
#model = LinearRegression()
model = LinearRegression(fit_intercept=False)

In [51]:
#　モデルの学習　←　パラメータの調整
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [52]:
# 調整後のパラメータ
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [53]:
model.intercept_

0.0

In [54]:
# 予測精度　←　決定係数 :0~1(0:論外、１：良い)
model.score(X,y)


0.6923076923076924

In [55]:
# 予測値の計算 predict
x = np.array([[1,2,3]])

In [58]:
y_pred = model.predict(x)
y_pred

array([[3.]])